In [9]:
import numpy as np

# Data points
X = np.array([7,10,24,37,75])
Y = np.array([4.5,6.8,9.2,3.7,9.4])

# Stack the design matrix with a column of ones (for the inetrcept)
A = np.vstack([X,np.ones(len(X))]).T

print("X:")
print(X)

print("Y:")
print(Y)

print("A:")
print(A)

X:
[ 7 10 24 37 75]
Y:
[4.5 6.8 9.2 3.7 9.4]
A:
[[ 7.  1.]
 [10.  1.]
 [24.  1.]
 [37.  1.]
 [75.  1.]]


In [10]:
# Solve using least squares
m,c = np.linalg.lstsq(A,Y,rcond=None)[0]
print(f"Slope:{m},Intercept:{c}")

Slope:0.04413275385223232,Intercept:5.3695377321216915
