Linear Algebra in Python

In [1]:
import numpy as np

In [3]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

In [4]:
print(v1)
print (v2)

[1 2 3]
[4 5 6]


In [5]:
v_add = v1 + v2
v_sub = v1 - v2

In [7]:
print(v_add)
print(v_sub)

[5 7 9]
[-3 -3 -3]


In [15]:
scalar = 2
v_scaled = scalar * v1

In [16]:
print(v_scaled)

[2 4 6]


In [17]:
dot_product = np.dot(v1,v2)

In [18]:
print(dot_product)

32


In [20]:
magnitude_v1 = np.linalg.norm(v1)
print(magnitude_v1)

3.7416573867739413


In [22]:
A = np.array([[1,2,3],[4,5,6]])
print(A)
print ()

B = np.array([[7,8,9],[10,11,12],[13,14,15]])
print(B)
print()

[[1 2 3]
 [4 5 6]]

[[ 7  8  9]
 [10 11 12]
 [13 14 15]]



In [25]:
C = np.array([[1,2,3],[4,5,6]])
matrix_add = A + C
matrix_sub = A - C

print("A+C=", matrix_add)
print("A-C=", matrix_sub)

A+C= [[ 2  4  6]
 [ 8 10 12]]
A-C= [[0 0 0]
 [0 0 0]]


In [30]:
A = np.array ([[2,1],[1,2]])
e_value, e_vector = np.linalg.eig(A)

In [31]:
print("eigenvalue:",e_value)
print("eigenvector:",e_vector)

eigenvalue: [3. 1.]
eigenvector: [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [33]:
A = np.array([[4,7],[2,6]])
A_inv = np.linalg.inv(A)

print(A)
print(A_inv)

[[4 7]
 [2 6]]
[[ 0.6 -0.7]
 [-0.2  0.4]]


In [34]:
identity = np.dot(A,A_inv)
print(identity)

[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]
